# Generated by Django 3.0 on 2020-09-17 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 3, 14, 395244), verbose_name='Hora'),
        ),
    ]
