# Generated by Django 3.0 on 2020-09-20 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0002_auto_20200917_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 20), null=True, verbose_name='Fecha de Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 27, 24, 615664), verbose_name='Hora'),
        ),
    ]
